name: Deployment
on:
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checking out repository
       uses: actions/checkout@v4
     
     - name: Building Backend Docker image 
       run:  docker build -f ./backend/dockerfile -t backend:latest ./backend
   
     - name: verify images
       run: docker images -a
